import { Inter } from "next/font/google";
import Link from "next/link";
import Provider from "./Provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-800 text-slate-100`}>
        <div className="max-w-7xl mx-auto">
          <nav>
            <ul className="flex gap-5 p-5 ">
              <li>
                <Link href={"/"}>Home</Link>
              </li>
              <li>
                <Link href={"/anime"}>Anime</Link>
              </li>
            </ul>
          </nav>
          <main className="p-5">
            <Provider>{children}</Provider>
          </main>
        </div>
      </body>
    </html>
  );
}
