import { Inter } from "next/font/google";
import Link from "next/link";
import Provider from "./Provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Provider>
          <div className="max-w-7xl mx-auto">
            <nav>
              <ul className="flex gap-5 p-5 ">
                <li>
                  <Link href={"/dashboard"}>Dashboard</Link>
                </li>
                <li>
                  <Link href={"/movie"}>Movie</Link>
                </li>
                <li>
                  <Link href={"/anime"}>Anime</Link>
                </li>
              </ul>
            </nav>
            <main className="p-5">{children}</main>
          </div>
        </Provider>
      </body>
    </html>
  );
}
